<a href="https://colab.research.google.com/github/Mehhhhull/numpy-yt/blob/main/arraysindexingandslicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

**Numpy indexing and slicing of vectors**

In [6]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[1:5]

array([12, 13, 14, 15])

NUMPY INDEXING AND SLICING OF MATRIX

In [9]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0,0]

np.int64(1)

In [11]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [12]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [13]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [15]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])