<a href="https://colab.research.google.com/github/Mehhhhull/numpy-yt/blob/main/arrayoperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

**ARRAY OPERATIONS**

In [23]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])


In [24]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [25]:
a1-a2

array([-5, -5, -5, -5, -5])

In [26]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [27]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [28]:
a1//a2

array([0, 0, 0, 0, 0])

In [29]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [30]:
l=[10,20,30,40]
arr=np.array(l)

In [31]:
arr+10

array([20, 30, 40, 50])

**DEEP AND SHALLOW COPY**:

In [32]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

Shallow copy:apni alag jagah bana leta h ram m original ko change ni krtaaaa.:array
deep copy:array m se slice out kroge toh main array m b hoga:list a.copy

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a[4:6]*10

array([50, 60])

In [36]:
a
b=a

In [37]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

a.copy to create shallow copy.

**MATRIX OPS**

In [40]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
A @ B

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [45]:
A.T

array([[1, 3],
       [2, 4]])

**ADVANCE ARRAY MANIPULATION**

Stacking Array:Have to use vectors, cant use matrix

In [49]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])

In [51]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [54]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [56]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [59]:
a=np.vsplit(c,2)

In [61]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
