<a href="https://colab.research.google.com/github/Mehhhhull/numpy-yt/blob/main/numpy(arrays)_yt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Array Creation**

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
a=[1,2,3,4,"hello"]
a

[1, 2, 3, 4]

In [ ]:
np.array(a)

array([1, 2, 3, 4])

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array generational functions**

In [ ]:
arr=np.arange(1,11,2)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.zeros((6,6))
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr=np.ones((6))
arr

array([1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr=np.linspace(1,5,2)
arr

array([1., 5.])

**Random Generation Function**

In [ ]:
np.random.rand(5)

array([0.16772703, 0.21447138, 0.31557936, 0.94420692, 0.51781824])

In [ ]:
np.random.randint(10,20,10)

0

**Array Attributes**

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

In [ ]:
arr.dtype

**Array Methods**

In [ ]:
arr

array([1., 5.])

In [ ]:
arr.min()

np.float64(1.0)

In [ ]:
arr.max()

np.float64(5.0)

In [ ]:
arr.sum()

In [ ]:
np.sum(arr,axis=0)

np.float64(6.0)

In [ ]:
arr.mean()

<function ndarray.mean>

In [ ]:
arr.std()

np.float64(2.0)

In [ ]:
arr.argmax()

np.int64(1)

In [ ]:
arr.argmin()

np.int64(0)

**Array Reshaping And Resizing**

In [ ]:
arr=np.arange(1,31)
arr=arr.reshape(6,5)

In [ ]:
arr

array([1., 5.])